version: '3.8'
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
          - POSTGRES_USER=dev_user
          - POSTGRES_PASSWORD=dev_password
        ports:
          - '5432:5432'
        volumes: 
          - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
          - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local